# Generated by Django 4.2.4 on 2023-09-18 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscripe',
        ),
        migrations.AddField(
            model_name='subscription',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sub_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='название подписки'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sub_status',
            field=models.BooleanField(default=True, verbose_name='наличие подписки'),
        ),
    ]
