# Generated by Django 4.2.4 on 2023-09-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_subscription_subscripe_subscription_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='sub_status',
        ),
    ]
