# Generated by Django 4.2.4 on 2023-09-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_curse_sub_type_subscription'),
        ('users', '0006_remove_subscription_sub_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subscription',
        ),
    ]
