# Generated by Django 4.2.4 on 2023-09-04 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, verbose_name='пользователь')),
                ('pay_day', models.DateField(max_length=30, verbose_name='дата оплаты')),
                ('pay_check', models.BooleanField(default=True, verbose_name='оплата курса или урока')),
                ('pay_summ', models.IntegerField(verbose_name='сумма оплаты')),
                ('pay_way', models.CharField(max_length=40, verbose_name='способ оплаты')),
                ('curse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.curse')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lesson')),
            ],
            options={
                'verbose_name': 'оплата',
                'verbose_name_plural': 'оплаты',
            },
        ),
    ]
