# Generated by Django 4.2.4 on 2023-09-04 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.curse', verbose_name='урок'),
        ),
    ]
