# Generated by Django 4.2.4 on 2023-09-04 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_lesson_lesson_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='curse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.curse'),
        ),
    ]
