# Generated by Django 4.2.4 on 2023-09-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_curse_owner_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='curse',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
